/*------------------------------------------------------------
Author: Sathvik Voola
Company: Coforge
Description: A constant class to replace any hard coded keyword in apex classes.
Inputs: None
Test Class: ConstantsTest
History
<Date>      <Authors Name>  	<Brief Description of Change>
16-11-2021   Sathvik Voola       Initial Draft
------------------------------------------------------------*/
public with sharing class Constants{

	public static final String TYPE_BOOLEAN = 'Boolean';
	public static final String TYPE_TEXT = 'Text';
	public static final String TYPE_TEXTAREA = 'TextArea';
	public static final String TYPE_SELECT = 'Select';
	public static final String TYPE_CURRENCY = 'Currency';
	public static final String TYPE_PICKLIST = 'PICKLIST';
	public static final String TYPE_INTEGER = 'Integer';
	public static final String SEMI_COLON = ';';
	public static final String TYPE_COMBOBOX = 'ComboBox';
	public static final String TYPE_DATE = 'Date';
	
}