/*------------------------------------------------------------
Author: Darshan Singh
Company: Coforge
Description: A test class for the class 'Exception Handler Class'
Inputs: None
History
<Date>       <Authors Name>     <Brief Description of Change>
10/11/2021   Darshan Singh      Initial Draft
------------------------------------------------------------*/
@isTest
public class MyException_Test {
	@isTest
    public static void getErrorMessageTest()
    {
        MyException.getErrorMessage();
    }
}